"""
Django settings for django_linebot project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
############################################################################################
# app relative settings
DEBUG = True

ALLOWED_HOSTS = ['87bc-111-185-172-45.ngrok-free.app']

CSRF_TRUSTED_ORIGINS = [
    'https://87bc-111-185-172-45.ngrok-free.app',  # 添加你的 ngrok 域名
]

CHANNEL_SECRET = '585e2e67e993283fb0ac9514603d0eb8'
CHANNEL_ACCESS_TOKEN = '94m0L33buDymoj7HPe/U7oXbR0np9GUA2OqedFrR0SBXT2xVpWP30ChIDVjSD2rfzRxWxF9esbDxJmZ/Rng355Z+nrIeXhGwtE1yD4itYJsinR9jJt4Q73Nwgrq7lbdBKUmWp8k14+8W1cjxvM2QoQdB04t89/1O/w1cDnyilFU='

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


############################################################################################

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sixm6q7r!5zhe1sizyw421%o-t)ns9@u@6epixd80*4e*!*rb$'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'hrapp',
    'django_elasticsearch_dsl',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_linebot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_linebot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  # 数据库名称，与 docker-compose.yml 中 POSTGRES_DB 一致
        'USER': 'postgres',  # 数据库用户，与 docker-compose.yml 中 POSTGRES_USER 一致
        'PASSWORD': 'postgres',  # 数据库密码，与 docker-compose.yml 中 POSTGRES_PASSWORD 一致
        'HOST': 'db',  # 在 docker-compose.yml 中定义的服务名称
        'PORT': '5400',  # PostgreSQL 的默认端口
    }
}


ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'http://elastic:asdf123520@elasticsearch:9000',  # 使用基本身份验证
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # 确保这个路径是正确的
# ]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
