# Generated by Django 4.2.15 on 2024-08-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_customer_uploadedppt_patent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linemessage',
            old_name='message_text',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='linemessage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='linemessage',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hrapp.customer'),
        ),
    ]
