# Generated by Django 4.2.15 on 2024-08-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_alter_linemessage_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
