# Generated by Django 4.2.15 on 2024-08-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='embedding',
        ),
    ]
